AWS_KEY_PAIR_PRIVATE_PATH = "./keys/ap-south-2-key"
AWS_KEY_PAIR_PUBLIC_PATH = "./keys/ap-south-2-key.pub"
AWS_KEY_PAIR_NAME = "ap-south-2-key"
AWS_REGION = "ap-south-1"
AWS_PROFILE = "nagasai"
EC2_USER = "ubuntu"
